apiVersion: v1
kind: Service
metadata:
  name: {{ include "fliegengitter.frontend.name" . }}
  labels:
    {{- include "fliegengitter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fliegengitter.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
